---
functional:
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - В каталоге и карточке товара должны выводится название, рейтинг, цена, скидочная цена
  - Пользователь должен иметь возможность просматривать каталог товаров постраничным выводом
  - Пользователь должен иметь возможность после добавления товара в корзину продолжить покупки на сайте
  - Пользователь должен иметь возможность удалить любой добавленный товар из корзины
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
  - Товары из корзины должны сохраняться в сессии браузера пользователя
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен обработывать большое количество трафика пользователей
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь мобильную версию
  - Сайт должен иметь адаптивную верстку
  - Сайт интернет-магазина должен быть SPA-приложением
implicit:
  - Пользователь должен иметь возможность подтвердить или отменить выбранный заказ



